name: Build Packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Yarn
      run: yarn install
    - name: Build For Linux
      id: build-linux
      run: |
        yarn build:bundle
        yarn build:linux --publish never
    - name: Pack Build Files
      run: |
        mkdir ~/Stoat-linux-AppImage
        mv dist/*.AppImage ~/Stoat-linux-AppImage
        mkdir ~/Stoat-linux
        mv dist/*.tar.gz ~/Stoat-linux
    - name: Publish AppImage
      uses: actions/upload-artifact@v4
      with:
        path: ~/Stoat-linux-AppImage
        name: Stoat-linux-AppImage
    - name: Publish Tarfile
      uses: actions/upload-artifact@v4
      with:
        path: ~/Stoat-linux/
        name: Stoat-linux
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.1
    - name: Install Yarn
      run: yarn install
    - name: Build For Windows
      id: build-windows
      run: |
        yarn build:bundle
        yarn build:windows --publish never
    - name: Pack Build Files
      run: |
        mkdir D:\a\desktop\Stoat-windows
        mv D:\a\desktop\desktop\dist\win-unpacked\* D:\a\desktop\Stoat-windows
        mkdir D:\a\desktop\Stoat-windows-Setup
        mv D:\a\desktop\desktop\dist\*.exe D:\a\desktop\Stoat-windows-Setup.exe
        mkdir D:\a\desktop\Stoat-windows-appx
        mv D:\a\desktop\desktop\dist\*.appx D:\a\desktop\Stoat-windows-appx
    - name: Publish Zipfile
      uses: actions/upload-artifact@v4
      with:
        path: D:\a\desktop\Stoat-windows
        name: Stoat-windows
    - name: Publish Installer
      uses: actions/upload-artifact@v4
      with:
        path: D:\a\desktop\Stoat-windows-Setup.exe
        name: Stoat-windows-Setup
    - name: Publish Appx
      uses: actions/upload-artifact@v4
      with:
        path: D:\a\desktop\Stoat-windows-appx
        name: Stoat-windows-appx
  build-macos:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4
    - name: Install Yarn
      run: yarn install
    - name: Build For macOS
      run: |
        yarn build:bundle
        yarn build:mac --publish never
        mv dist/*-universal.dmg ~/Stoat-macOS-universal.dmg
    - name: Publish Build Files
      uses: actions/upload-artifact@v4
      with:
        path: ~/Stoat-macOS-universal.dmg
        name: Stoat-macOS-universal
